# Generated by Django 5.0.7 on 2024-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
